remote_theme: pmarsceill/just-the-docs
title: Github for collaborative documentation
description: Tutorials and a place to practice conttributing to documentation hosted on github pages
# Aux links for the upper right navigation
baseurl: "/github-for-collaborative-documentation" # the subpath of your site, e.g. /blog
url: "https://cassgvp.github.io" # the base hostname & protocol for your site, e.g. http://example.com
aux_links:
  "View on GitHub":
    - "//github.com/cassgvp/github-for-collaborative-documentation"
# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2020 Cassandra Gould van Praag. Distributed under a <a href=\"https://cassgvp.github.io/github-for-collaborative-documentation/docs/LICENSE.html\">CC-BY-3.0 license.</a>"
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/cassgvp/github-for-collaborative-documentation" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
color_scheme: cassgvp
logo: /img/logo2.png
